version: "1.0.0"
services:
  pisifer:
    build:
      context: server
      dockerfile: DockerFile
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports: [ '5002:5000' ]
    volumes: [ './server:/app' ]
